

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app          
      - ./data:/app/data  
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment: 
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      - db

    
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: 
    
    