// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package invoicer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightSolutionQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	DepartureDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightSolutionQuery) Reset() {
	*x = FlightSolutionQuery{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightSolutionQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSolutionQuery) ProtoMessage() {}

func (x *FlightSolutionQuery) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSolutionQuery.ProtoReflect.Descriptor instead.
func (*FlightSolutionQuery) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *FlightSolutionQuery) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *FlightSolutionQuery) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *FlightSolutionQuery) GetDepartureDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureDate
	}
	return nil
}

type FlightSolutions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AirlineCode   string                 `protobuf:"bytes,1,opt,name=airline_code,json=airlineCode,proto3" json:"airline_code,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	FareClass     string                 `protobuf:"bytes,3,opt,name=fare_class,json=fareClass,proto3" json:"fare_class,omitempty"`
	Aircraft      string                 `protobuf:"bytes,4,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightSolutions) Reset() {
	*x = FlightSolutions{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightSolutions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSolutions) ProtoMessage() {}

func (x *FlightSolutions) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSolutions.ProtoReflect.Descriptor instead.
func (*FlightSolutions) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *FlightSolutions) GetAirlineCode() string {
	if x != nil {
		return x.AirlineCode
	}
	return ""
}

func (x *FlightSolutions) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FlightSolutions) GetFareClass() string {
	if x != nil {
		return x.FareClass
	}
	return ""
}

func (x *FlightSolutions) GetAircraft() string {
	if x != nil {
		return x.Aircraft
	}
	return ""
}

type FlightSolutionsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solutions     []*FlightSolutions     `protobuf:"bytes,1,rep,name=solutions,proto3" json:"solutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightSolutionsList) Reset() {
	*x = FlightSolutionsList{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightSolutionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSolutionsList) ProtoMessage() {}

func (x *FlightSolutionsList) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSolutionsList.ProtoReflect.Descriptor instead.
func (*FlightSolutionsList) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *FlightSolutionsList) GetSolutions() []*FlightSolutions {
	if x != nil {
		return x.Solutions
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n" +
	"\x13FlightSolutionQuery\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\x12A\n" +
	"\x0edeparture_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureDate\"\x85\x01\n" +
	"\x0fFlightSolutions\x12!\n" +
	"\fairline_code\x18\x01 \x01(\tR\vairlineCode\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x1d\n" +
	"\n" +
	"fare_class\x18\x03 \x01(\tR\tfareClass\x12\x1a\n" +
	"\baircraft\x18\x04 \x01(\tR\baircraft\"E\n" +
	"\x13FlightSolutionsList\x12.\n" +
	"\tsolutions\x18\x01 \x03(\v2\x10.FlightSolutionsR\tsolutions2R\n" +
	"\fSearchFlight\x12B\n" +
	"\x14GetAggregatedFlights\x12\x14.FlightSolutionQuery\x1a\x14.FlightSolutionsListB\x17Z\x15grpc-project/invoicerb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(*FlightSolutionQuery)(nil),   // 0: FlightSolutionQuery
	(*FlightSolutions)(nil),       // 1: FlightSolutions
	(*FlightSolutionsList)(nil),   // 2: FlightSolutionsList
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	3, // 0: FlightSolutionQuery.departure_date:type_name -> google.protobuf.Timestamp
	1, // 1: FlightSolutionsList.solutions:type_name -> FlightSolutions
	0, // 2: SearchFlight.GetAggregatedFlights:input_type -> FlightSolutionQuery
	2, // 3: SearchFlight.GetAggregatedFlights:output_type -> FlightSolutionsList
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
