// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: service.proto

package invoicer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchFlight_GetAggregatedFlights_FullMethodName = "/SearchFlight/GetAggregatedFlights"
)

// SearchFlightClient is the client API for SearchFlight service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchFlightClient interface {
	GetAggregatedFlights(ctx context.Context, in *FlightSolutionQuery, opts ...grpc.CallOption) (*FlightSolutionsList, error)
}

type searchFlightClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchFlightClient(cc grpc.ClientConnInterface) SearchFlightClient {
	return &searchFlightClient{cc}
}

func (c *searchFlightClient) GetAggregatedFlights(ctx context.Context, in *FlightSolutionQuery, opts ...grpc.CallOption) (*FlightSolutionsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightSolutionsList)
	err := c.cc.Invoke(ctx, SearchFlight_GetAggregatedFlights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchFlightServer is the server API for SearchFlight service.
// All implementations must embed UnimplementedSearchFlightServer
// for forward compatibility.
type SearchFlightServer interface {
	GetAggregatedFlights(context.Context, *FlightSolutionQuery) (*FlightSolutionsList, error)
	mustEmbedUnimplementedSearchFlightServer()
}

// UnimplementedSearchFlightServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchFlightServer struct{}

func (UnimplementedSearchFlightServer) GetAggregatedFlights(context.Context, *FlightSolutionQuery) (*FlightSolutionsList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAggregatedFlights not implemented")
}
func (UnimplementedSearchFlightServer) mustEmbedUnimplementedSearchFlightServer() {}
func (UnimplementedSearchFlightServer) testEmbeddedByValue()                      {}

// UnsafeSearchFlightServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchFlightServer will
// result in compilation errors.
type UnsafeSearchFlightServer interface {
	mustEmbedUnimplementedSearchFlightServer()
}

func RegisterSearchFlightServer(s grpc.ServiceRegistrar, srv SearchFlightServer) {
	// If the following call panics, it indicates UnimplementedSearchFlightServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchFlight_ServiceDesc, srv)
}

func _SearchFlight_GetAggregatedFlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightSolutionQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchFlightServer).GetAggregatedFlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchFlight_GetAggregatedFlights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchFlightServer).GetAggregatedFlights(ctx, req.(*FlightSolutionQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchFlight_ServiceDesc is the grpc.ServiceDesc for SearchFlight service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchFlight_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SearchFlight",
	HandlerType: (*SearchFlightServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAggregatedFlights",
			Handler:    _SearchFlight_GetAggregatedFlights_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
