// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package invoicer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAggregatedFlightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	DepartureDate string                 `protobuf:"bytes,3,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregatedFlightsRequest) Reset() {
	*x = GetAggregatedFlightsRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatedFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatedFlightsRequest) ProtoMessage() {}

func (x *GetAggregatedFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatedFlightsRequest.ProtoReflect.Descriptor instead.
func (*GetAggregatedFlightsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAggregatedFlightsRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetAggregatedFlightsRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *GetAggregatedFlightsRequest) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

type FlightSolutions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AirlineCode   string                 `protobuf:"bytes,1,opt,name=airline_code,json=airlineCode,proto3" json:"airline_code,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	FareClass     string                 `protobuf:"bytes,3,opt,name=fare_class,json=fareClass,proto3" json:"fare_class,omitempty"`
	Aircraft      string                 `protobuf:"bytes,4,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightSolutions) Reset() {
	*x = FlightSolutions{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightSolutions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightSolutions) ProtoMessage() {}

func (x *FlightSolutions) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightSolutions.ProtoReflect.Descriptor instead.
func (*FlightSolutions) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *FlightSolutions) GetAirlineCode() string {
	if x != nil {
		return x.AirlineCode
	}
	return ""
}

func (x *FlightSolutions) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FlightSolutions) GetFareClass() string {
	if x != nil {
		return x.FareClass
	}
	return ""
}

func (x *FlightSolutions) GetAircraft() string {
	if x != nil {
		return x.Aircraft
	}
	return ""
}

type GetAggregatedFlightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solutions     []*FlightSolutions     `protobuf:"bytes,1,rep,name=solutions,proto3" json:"solutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregatedFlightsResponse) Reset() {
	*x = GetAggregatedFlightsResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatedFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatedFlightsResponse) ProtoMessage() {}

func (x *GetAggregatedFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatedFlightsResponse.ProtoReflect.Descriptor instead.
func (*GetAggregatedFlightsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAggregatedFlightsResponse) GetSolutions() []*FlightSolutions {
	if x != nil {
		return x.Solutions
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\"p\n" +
	"\x1bGetAggregatedFlightsRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\x12%\n" +
	"\x0edeparture_date\x18\x03 \x01(\tR\rdepartureDate\"\x85\x01\n" +
	"\x0fFlightSolutions\x12!\n" +
	"\fairline_code\x18\x01 \x01(\tR\vairlineCode\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x1d\n" +
	"\n" +
	"fare_class\x18\x03 \x01(\tR\tfareClass\x12\x1a\n" +
	"\baircraft\x18\x04 \x01(\tR\baircraft\"N\n" +
	"\x1cGetAggregatedFlightsResponse\x12.\n" +
	"\tsolutions\x18\x01 \x03(\v2\x10.FlightSolutionsR\tsolutions2c\n" +
	"\fSearchFlight\x12S\n" +
	"\x14GetAggregatedFlights\x12\x1c.GetAggregatedFlightsRequest\x1a\x1d.GetAggregatedFlightsResponseB\x17Z\x15grpc-project/invoicerb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(*GetAggregatedFlightsRequest)(nil),  // 0: GetAggregatedFlightsRequest
	(*FlightSolutions)(nil),              // 1: FlightSolutions
	(*GetAggregatedFlightsResponse)(nil), // 2: GetAggregatedFlightsResponse
}
var file_service_proto_depIdxs = []int32{
	1, // 0: GetAggregatedFlightsResponse.solutions:type_name -> FlightSolutions
	0, // 1: SearchFlight.GetAggregatedFlights:input_type -> GetAggregatedFlightsRequest
	2, // 2: SearchFlight.GetAggregatedFlights:output_type -> GetAggregatedFlightsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
